const express=require("express");const router=express.Router();
const User=require("../models/User");const jwt=require("jsonwebtoken");
router.post("/register",async(req,res)=>{const {name,email,password}=req.body;
try{const user=new User({name,email,password});await user.save();
const token=jwt.sign({id:user._id},process.env.JWT_SECRET);res.json({token,user:{name,email}});
}catch(err){res.status(400).json({error:"Email already exists"});}});
router.post("/login",async(req,res)=>{const {email,password}=req.body;
const user=await User.findOne({email});if(!user)return res.status(400).json({error:"User not found"});
const valid=await user.comparePassword(password);if(!valid)return res.status(400).json({error:"Incorrect password"});
const token=jwt.sign({id:user._id},process.env.JWT_SECRET);res.json({token,user:{name:user.name,email}});});
module.exports=router;